version: '3'
services:
  packet-capture-engine:
    container_name: pcap-engine
    image: pacp-engine:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    environment:
      - REDIS_HOST=redis:6379
    networks:
      - packet-src-network
      - packet-dst-network

  redis:
    container_name: pcap-redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    environment:
      - REDIS_URL=0.0.0.0
    networks:
      - packet-src-network

  packet-dst:
    container_name: pcap-dst
    image: pkt-dst
    cap_add:
      - NET_ADMIN
    build:
      context: ./
      dockerfile: ./docker/dst-Dockerfile
    links:
      - packet-capture-engine
    networks:
      - packet-dst-network

  packet-src:
    privileged: true
    cap_add:
      - NET_ADMIN
    container_name: pcap-src
    image: pkt-src
    build:
      context: ./
      dockerfile: ./docker/src-Dockerfile
    links:
      - packet-capture-engine
    networks:
      - packet-src-network

networks:
  packet-src-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  packet-dst-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
