version: '3'
services:
  packet-capture-engine:
    container_name: pcap-engine
    image: pacp-engine:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST=redis:6379
    networks:
      packet-src-network:
        ipv4_address: 192.168.10.3
      packet-dst-network:
        ipv4_address: 192.168.11.3

  redis:
    container_name: pcap-redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    environment:
      - REDIS_URL=0.0.0.0
    networks:
      packet-src-network:
        ipv4_address: 192.168.10.4

  packet-dst:
    container_name: pcap-dst
    image: pkt-dst
    privileged: true
    cap_drop:
      - NET_ADMIN
    build:
      context: ./
      dockerfile: ./docker/dst-Dockerfile
    links:
      - packet-capture-engine
    networks:
      packet-dst-network:
        ipv4_address: 192.168.11.2

  packet-src:
    container_name: pcap-src
    image: pkt-src
    privileged: true
    cap_drop:
      - NET_ADMIN
    depends_on:
      - "packet-dst"
    build:
      context: ./
      dockerfile: ./docker/src-Dockerfile
    links:
      - packet-capture-engine
    networks:
      packet-src-network:
        ipv4_address: 192.168.10.2

networks:
  packet-src-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  packet-dst-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24

